apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:  # This 'spec' was missing in the error!
      containers:
        - name: product-service
          image: tanviisahuu/petopia_product:latest
          ports:
            - containerPort: 8002
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
            requests:
              memory: "256Mi"
              cpu: "250m"
          env:
            - name: DEBUG
              value: "true"
            - name: DB_HOST
              value: "wj48254.central-india.azure"
            - name: DB_NAME
              value: "pet_db"
            - name: DB_SCHEMA
              value: "pet_schema1"
            - name: DB_WAREHOUSE
              value: "pet_dw"
            - name: DB_USER
              value: "TanviiSahuu"
            - name: DB_PASSWORD
              value: "Snowflake@2025"
---
apiVersion: v1
kind: Service
metadata:
  name: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8002
      targetPort: 8002
  type: ClusterIP  # ✅ No external exposure needed