# Generated by Django 5.1.6 on 2025-03-08 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_pd', '0002_alter_productcategory_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productcategory',
            old_name='id',
            new_name='category_id',
        ),
    ]
