# Generated by Django 5.1.6 on 2025-03-08 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_pd', '0004_rename_category_product_category_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category_id',
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(db_column='CATEGORY', default=1, on_delete=django.db.models.deletion.CASCADE, to='app_pd.productcategory'),
            preserve_default=False,
        ),
    ]
