apiVersion: v1
kind: Service
metadata:
  name: pet-product-service
spec:
  type: NodePort
  selector:
    app: pet-product
  ports:
    - protocol: TCP
      port: 8002       # Service port for internal communication
      targetPort: 8002 # Container's port
  type: ClusterIP   # External port (customize or omit to auto-assign)
